name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Lint
        run: uv run --with nox -m nox -s lint
      - name: Format check
        run: uv run --with nox -m nox -s format
      - name: Typing check
        run: uv run --with nox -m nox -s types
      - name: Check versions match
        run: uv run --with nox -m nox -s check_version

  tests:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Tests
        run: uv run --with nox -m nox -s tests
